// Package manifest provides read/write/diff operations for tass.manifest.yaml.
// The manifest is the source of truth for which capabilities have been reviewed
// in a repository. It lives committed in the repo alongside the source code.
package manifest

import (
	"fmt"
	"os"
	"time"

	"github.com/tass-security/tass/pkg/contracts"
	"gopkg.in/yaml.v3"
)

const manifestVersion = "1"

// ManifestEntry is one capability entry in the manifest file.
// It extends Capability with review metadata.
type ManifestEntry struct {
	ID            string                 `yaml:"id"`
	Name          string                 `yaml:"name"`
	Category      contracts.CapCategory  `yaml:"category"`
	Source        contracts.DetectionLayer `yaml:"source"`
	ConfirmedBy   string                 `yaml:"confirmed_by,omitempty"`
	ConfirmedAt   *time.Time             `yaml:"confirmed_at,omitempty"`
	FirstDetected *time.Time             `yaml:"first_detected,omitempty"`
	Note          string                 `yaml:"note,omitempty"`
	Locations     []contracts.CodeLocation `yaml:"locations,omitempty"`
	Status        string                 `yaml:"status,omitempty"` // "confirmed", "auto_detected", "reverted"
}

// Manifest is the complete tass.manifest.yaml structure.
type Manifest struct {
	Version      string          `yaml:"version"`
	GeneratedAt  time.Time       `yaml:"generated_at"`
	Repo         string          `yaml:"repo"`
	Capabilities []ManifestEntry `yaml:"capabilities"`
}

// Load reads and parses a manifest file from the given path.
func Load(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("manifest.Load: read %q: %w", path, err)
	}
	return LoadBytes(data)
}

// LoadBytes parses a manifest from raw YAML bytes.
func LoadBytes(data []byte) (*Manifest, error) {
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("manifest.LoadBytes: parse yaml: %w", err)
	}
	if m.Version == "" {
		m.Version = manifestVersion
	}
	return &m, nil
}

// Save writes the manifest to a file with a descriptive header comment.
func Save(m *Manifest, path string) error {
	data, err := Marshal(m)
	if err != nil {
		return fmt.Errorf("manifest.Save: %w", err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("manifest.Save: write %q: %w", path, err)
	}
	return nil
}

// Marshal serializes the manifest to YAML bytes with a header comment.
func Marshal(m *Manifest) ([]byte, error) {
	body, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("manifest.Marshal: %w", err)
	}

	header := `# tass.manifest.yaml — Behavioral capability manifest
# Generated by TASS (Trusted AI Security Scanner) — https://tass.dev
#
# This file tracks every capability this repository has been reviewed for.
# Commit and review this file just like you would a lockfile.
#
# Each entry represents a detected capability that a developer has confirmed
# or that was auto-detected during 'tass init'. Review before committing.
#
# Sections:
#   id:           Deterministic stable identifier (category:lang:module/symbol)
#   name:         Human-readable capability name
#   category:     external_dependency | external_api | database_operation |
#                 network_access | filesystem_operation | privilege_pattern
#   source:       layer0_dependency (from dep files) | layer1_ast (from source)
#   confirmed_by: GitHub username of reviewer
#   confirmed_at: ISO 8601 timestamp of review
#   note:         Optional context for why this capability exists
#   status:       confirmed | auto_detected | reverted
#
`
	return append([]byte(header), body...), nil
}

// Diff returns the capabilities in detected that are NOT present in the manifest.
// Matching is done on capability ID only (set difference). This is the core
// mechanic: if a capability ID is in the manifest, it's known. If not, it's novel.
func Diff(detected contracts.CapabilitySet, existing *Manifest) []contracts.Capability {
	known := make(map[string]struct{}, len(existing.Capabilities))
	for _, e := range existing.Capabilities {
		known[e.ID] = struct{}{}
	}

	var novel []contracts.Capability
	for _, cap := range detected.Capabilities {
		if _, ok := known[cap.ID]; !ok {
			novel = append(novel, cap)
		}
	}
	return novel
}

// FromCapabilitySet creates a Manifest from a CapabilitySet.
// All capabilities are given status "auto_detected" — intended for use by
// `tass init` to generate the initial manifest from an existing repo.
func FromCapabilitySet(cs contracts.CapabilitySet, repo string) *Manifest {
	now := time.Now().UTC()
	entries := make([]ManifestEntry, 0, len(cs.Capabilities))
	for _, cap := range cs.Capabilities {
		firstDetected := now
		entries = append(entries, ManifestEntry{
			ID:            cap.ID,
			Name:          cap.Name,
			Category:      cap.Category,
			Source:        cap.Source,
			FirstDetected: &firstDetected,
			Status:        "auto_detected",
			Locations:     []contracts.CodeLocation{cap.Location},
		})
	}
	return &Manifest{
		Version:      manifestVersion,
		GeneratedAt:  now,
		Repo:         repo,
		Capabilities: entries,
	}
}
