package github

import (
	"fmt"
	"strings"
)

// AISignal is the result of AI-authorship detection on a pull request.
// Detection is based purely on GitHub webhook metadata and commit history —
// no AST scanning or static analysis is performed.
type AISignal struct {
	// IsAIGenerated is true when at least one definitive heuristic matched
	// (author login or commit message trailer). The velocity heuristic alone
	// does not set this flag — it only contributes an informational signal.
	IsAIGenerated bool
	// Signals lists each matched heuristic in plain English, for display in
	// the PR comment badge.
	Signals []string
}

// CommitMeta holds the minimal commit data needed for AI detection.
// Populated from GET /repos/{owner}/{repo}/pulls/{n}/commits.
type CommitMeta struct {
	// Message is the full commit message including trailers.
	Message string
	// AuthorLogin is the GitHub login of the commit author (empty when the
	// commit is not associated with a GitHub account).
	AuthorLogin string
}

// knownAILogins is the set of lowercase GitHub login prefixes known to be
// AI agents or automation bots. The "[bot]" suffix is stripped before matching.
var knownAILogins = []string{
	"dependabot",
	"github-actions",
	"renovate",
	"claude-code",
	"copilot",
	"github-copilot",
	"cursor",
	"devin-ai-integration",
	"sweep",
	"sweep-ai",
	"coderabbitai",
	"antigravity",
	"sourcery-ai",
	"tabnine",
	"cody",
	"amazonq",
	"aws-codewhisperer",
}

// aiCommitTrailers is the set of lowercase substrings that, when present in
// any commit message, indicate AI-generated or AI-assisted authorship.
var aiCommitTrailers = []string{
	"co-authored-by: github-copilot",
	"co-authored-by: github copilot",
	"co-authored-by: copilot",
	"co-authored-by: claude",
	"co-authored-by: cursor",
	"co-authored-by: devin",
	"co-authored-by: tabnine",
	"co-authored-by: cody",
	"generated-by: cursor",
	"generated-by: claude",
	"generated-by: copilot",
	"generated by github copilot",
	"generated by anthropic",
	"generated by openai",
	"🤖 generated",
	"[claude]",
	"[gpt]",
	"[ai generated]",
	"ai-generated:",
	"auto-generated by",
}

// velocityThreshold is the minimum total diff size (additions + deletions) that
// triggers the velocity informational signal. Velocity alone does NOT set
// IsAIGenerated — it supplements the author/message signals.
const velocityThreshold = 500

// DetectAI evaluates a pull request against known AI-authorship heuristics and
// returns an AISignal describing whether the PR appears AI-generated.
//
//   - prAuthorLogin: GitHub login of the PR opener (pull_request.user.login).
//   - commits: commits in the PR from the GitHub Commits API. May be nil —
//     author-only detection still runs.
//   - linesChanged: total additions + deletions across the PR.
func DetectAI(prAuthorLogin string, commits []CommitMeta, linesChanged int) AISignal {
	var signals []string

	// --- Heuristic 1: PR author is a known AI agent / bot login ---
	if norm := normaliseLogin(prAuthorLogin); norm != "" {
		if isKnownAILogin(norm) {
			signals = append(signals,
				"PR author login matches known AI agent: "+prAuthorLogin)
		}
	}

	// --- Heuristic 2: commit message attribution trailers ---
	for _, c := range commits {
		msgLow := strings.ToLower(c.Message)
		for _, trailer := range aiCommitTrailers {
			if strings.Contains(msgLow, trailer) {
				signals = append(signals,
					"Commit message contains AI attribution trailer: \""+trailer+"\"")
				break // one signal per commit is enough
			}
		}

		// Also check the per-commit author login (can differ from PR opener on
		// force-pushes or co-authored merges).
		if norm := normaliseLogin(c.AuthorLogin); norm != "" && norm != normaliseLogin(prAuthorLogin) {
			if isKnownAILogin(norm) {
				signals = append(signals,
					"Commit author login matches known AI agent: "+c.AuthorLogin)
			}
		}
	}

	// --- Heuristic 3: velocity — large diff (informational only) ---
	if linesChanged > velocityThreshold {
		signals = append(signals,
			fmt.Sprintf("Large diff: %d lines changed (velocity signal — informational only)", linesChanged))
	}

	// IsAIGenerated is true only when a definitive heuristic (not velocity alone) fired.
	isAI := false
	for _, s := range signals {
		if !strings.HasPrefix(s, "Large diff:") {
			isAI = true
			break
		}
	}

	return AISignal{IsAIGenerated: isAI, Signals: signals}
}

// isKnownAILogin returns true if the normalised login matches or is prefixed by
// any entry in knownAILogins.
func isKnownAILogin(norm string) bool {
	for _, known := range knownAILogins {
		if norm == known || strings.HasPrefix(norm, known) {
			return true
		}
	}
	return false
}

// normaliseLogin strips the "[bot]" suffix and lowercases a GitHub login for
// comparison against knownAILogins.
func normaliseLogin(login string) string {
	return strings.TrimSuffix(strings.ToLower(strings.TrimSpace(login)), "[bot]")
}
