package policy

import (
	"encoding/json"
	"strings"
	"time"

	"github.com/tass-security/tass/pkg/contracts"
	"github.com/tass-security/tass/pkg/manifest"
)

// awsServiceMap maps known boto3/AWS capability name fragments to IAM service prefixes.
var awsServiceMap = map[string]string{
	"s3":               "s3",
	"dynamodb":         "dynamodb",
	"sqs":              "sqs",
	"sns":              "sns",
	"lambda":           "lambda",
	"ec2":              "ec2",
	"bedrock":          "bedrock",
	"bedrock-runtime":  "bedrock",
	"iam":              "iam",
	"sts":              "sts",
	"kms":              "kms",
	"secretsmanager":   "secretsmanager",
	"ssm":              "ssm",
	"cloudwatch":       "cloudwatch",
	"logs":             "logs",
	"ecs":              "ecs",
	"ecr":              "ecr",
	"cloudformation":   "cloudformation",
	"kinesis":          "kinesis",
	"firehose":         "firehose",
	"athena":           "athena",
	"glue":             "glue",
	"rekognition":      "rekognition",
	"textract":         "textract",
	"comprehend":       "comprehend",
	"polly":            "polly",
	"transcribe":       "transcribe",
	"translate":        "translate",
}

// iamStatement is one IAM policy statement.
type iamStatement struct {
	Sid      string   `json:"Sid"`
	Effect   string   `json:"Effect"`
	Action   []string `json:"Action"`
	Resource string   `json:"Resource"`
}

// iamPolicy is the full IAM policy document.
type iamPolicy struct {
	Version   string         `json:"Version"`
	Statement []iamStatement `json:"Statement,omitempty"`
}

// GenerateIAMPolicy creates an AWS IAM policy JSON from a manifest.
// Capabilities that reference boto3/AWS services produce Allow statements.
// Returns an empty-statement policy when no AWS capabilities are found.
func GenerateIAMPolicy(m *manifest.Manifest, opts PolicyOpts) ([]byte, error) {
	_ = opts // reserved for future use

	servicesSeen := make(map[string]bool)
	for _, cap := range m.Capabilities {
		if cap.Category != contracts.CatNetworkAccess && cap.Category != contracts.CatExternalAPI {
			continue
		}
		// Match against known service names in the capability name or ID.
		nameLower := strings.ToLower(cap.Name)
		idLower := strings.ToLower(cap.ID)
		for svc, prefix := range awsServiceMap {
			if strings.Contains(nameLower, svc) || strings.Contains(idLower, svc) {
				servicesSeen[prefix] = true
			}
		}
	}

	policy := iamPolicy{Version: "2012-10-17"}

	if len(servicesSeen) > 0 {
		var actions []string
		for svc := range servicesSeen {
			actions = append(actions, svc+":*")
		}
		// Sort for stable output
		sortStrings(actions)
		policy.Statement = []iamStatement{
			{
				Sid:      "TASSGeneratedPolicy",
				Effect:   "Allow",
				Action:   actions,
				Resource: "*",
			},
		}
	}

	// Add generator metadata as a comment-like field in a wrapper.
	type policyWithMeta struct {
		iamPolicy
		// Non-standard field — tools like IAM Policy Simulator will ignore it.
		TassGeneratedAt string `json:"_tass_generated_at,omitempty"`
		TassNote        string `json:"_tass_note,omitempty"`
	}

	wrapped := policyWithMeta{
		iamPolicy:       policy,
		TassGeneratedAt: time.Now().UTC().Format(time.RFC3339),
		TassNote:        "Generated by TASS from tass.manifest.yaml. Narrow Resource ARNs before deploying to production.",
	}

	return json.MarshalIndent(wrapped, "", "  ")
}

// sortStrings sorts a string slice in-place using insertion sort (no import needed for small slices).
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		key := s[i]
		j := i - 1
		for j >= 0 && s[j] > key {
			s[j+1] = s[j]
			j--
		}
		s[j+1] = key
	}
}
